# Generated by Django 3.0.5 on 2020-04-28 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_title', models.CharField(max_length=255, verbose_name='番組タイトル')),
                ('prog_channel', models.CharField(max_length=30, verbose_name='放送局')),
                ('prog_id', models.CharField(max_length=100, verbose_name='Radiko番組ID')),
                ('prog_ft', models.DateTimeField(verbose_name='放送開始日時')),
                ('prog_to', models.DateTimeField(verbose_name='放送終了日時')),
                ('prog_dur', models.IntegerField(verbose_name='放送時間')),
                ('prog_url', models.CharField(max_length=255, verbose_name='番組URL')),
                ('prog_desc', models.TextField(verbose_name='description')),
                ('prog_info', models.TextField(verbose_name='information')),
                ('prog_pfm', models.CharField(max_length=100, verbose_name='パーソナリティ')),
                ('prog_img', models.CharField(max_length=255, verbose_name='画像URL')),
                ('prog_hastag', models.CharField(max_length=255, verbose_name='Twitterハッシュタグ')),
                ('prog_file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['m4a'])])),
            ],
            options={
                'db_table': 'recfile',
            },
        ),
    ]
