# Generated by Django 3.0.5 on 2020-05-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recfile', '0002_auto_20200502_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recfile',
            old_name='prog_hastag',
            new_name='prog_hashtag',
        ),
    ]
